inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.1

# Project-specific overrides
Style/Documentation:
  Enabled: false

# Allow RSpec block lengths for test descriptions
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'it', 'specify', 'example', 'scenario', 'feature']

# Keep old params syntax for Rails 7.2 compatibility
Rails/DotSeparatedKeys:
  Enabled: false
